name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.8", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set min macOS version
        if: runner.os == 'macOS'
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=13.3" >> $GITHUB_ENV

      - name: Build and install
        run: |
          python -m pip install pytest
          pip install --verbose .

      - name: List installed files
        run: |
          pip show -f wickd
          ls -l
          ls -l wickd
          ls -R $(python -c "import site; print(site.getsitepackages()[0])")/wickd

      - name: Verify Python path
        run: |
          python -c "import sys; print(sys.path)"
          python -c "import wickd; print(wickd.__file__)"

      - name: Test
        run: python -m pytest
